# ### compose.yml
# ### version: "3.8"
# ### 
#
#

volumes:
  n8n_app_data:
  n8n_db_data:

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
      - EXECUTIONS_DATA_PRUNE=true
    volumes:
      - n8n_db_data:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    links:
      - postgres
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - NODE_ENV=production
      - NODE_FUNCTION_ALLOW_BUILTIN0=*
      - GENERIC_TIMEZONE=${TIMEZONE}
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=false
      - EXECUTIONS_DATA_PRUNE=true
      - N8N_EDITOR_BASE_URL = https://media39.ru/
      - WEBHOOK_URL0=${DOMAIN}
      - WEBHOOK_URL=https://media39.ru/
      - VUE_APP_URL_BASE_API=https://media39.ru/api/v1/
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n_app_data:/home/node/.n8n
      - /n8n-local-files:/files
      
